package com.dezonnov1.SpringGuideBotMinecraft.handler;

import com.dezonnov1.SpringGuideBotMinecraft.entity.BotAction;
import com.dezonnov1.SpringGuideBotMinecraft.entity.BotState;
import com.dezonnov1.SpringGuideBotMinecraft.entity.ServerProperty;
import com.dezonnov1.SpringGuideBotMinecraft.entity.UserSession;
import com.dezonnov1.SpringGuideBotMinecraft.repository.ServerPropertyRepository;
import com.dezonnov1.SpringGuideBotMinecraft.service.BotInfoHolder;
import com.dezonnov1.SpringGuideBotMinecraft.utils.ServerPropertiesUtils; // Импорт утилиты
import com.pengrad.telegrambot.model.Update;
import com.pengrad.telegrambot.model.request.InlineKeyboardButton;
import com.pengrad.telegrambot.model.request.InlineKeyboardMarkup;
import com.pengrad.telegrambot.model.request.ParseMode;
import com.pengrad.telegrambot.request.BaseRequest;
import com.pengrad.telegrambot.request.SendDocument;
import com.pengrad.telegrambot.request.SendMessage;
import lombok.RequiredArgsConstructor;
import org.springframework.context.annotation.Lazy;
import org.springframework.stereotype.Component;

import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;

/**
 * Хендлер возвращающий файл server.properties для указанной версии игры.
 * Отвечает за:
 * 1. Чтение версии игры
 * 2. Отправку файла server.properties нужной версии с комментариями
 */

@Component
@RequiredArgsConstructor
public class ServerPropertiesInputHandler implements DialogHandler {
    // Репозитории для работы с базой данных
    private final ServerPropertyRepository propertyRepository;
    private final BotInfoHolder botInfoHolder;

    // Хендлер для возврата в главное меню
    @Lazy
    private final StartHandler startHandler;

    // Метод возвращающий подходит ли этот хендлер для запроса пользователя
    @Override
    public boolean isApplicable(BotState currentState, Update update) {
        if (currentState != BotState.WAITING_FOR_SP_INPUT) {
            return false;
        }

        if (update.message() != null && update.message().document() != null) {
            return false;
        }
        return true;
    }

    @Override
    public HandlerResult handle(UserSession session, Update update) {
        Long chatId = session.getChatId();
        List<BaseRequest<?, ?>> responses = new ArrayList<>();

        // Логика отмены, если пользователь передумал
        if (update.callbackQuery() != null) {
            String data = update.callbackQuery().data();
            if (BotAction.CANCEL_INPUT.getCallbackData().equals(data)) {
                responses.add(new SendMessage(chatId, "Ввод отменен. Возвращаюсь в главное меню."));
                responses.add(startHandler.getWelcomeMessage(chatId));
                return new HandlerResult(responses, BotState.MAIN_MENU);
            }
        }

        if (update.message() != null && update.message().text() != null) {
            String versionInput = update.message().text().trim();
            List<ServerProperty> properties = propertyRepository.findAllByVersionName(versionInput);

            if (properties.isEmpty()) {
                SendMessage error = new SendMessage(chatId,
                        "Для версии " + versionInput + " у меня нет данных.\n" +
                                "Попробуйте, например: 1.16.5 или 1.20.1");
                // Кнопка отмены с действием CANCEL_INPUT
                InlineKeyboardMarkup keyboard = new InlineKeyboardMarkup(
                        new InlineKeyboardButton("В меню")
                                .callbackData(BotAction.CANCEL_INPUT.getCallbackData())
                );
                error.replyMarkup(keyboard);
                return new HandlerResult(List.of(error), null);
            }

            StringBuilder sb = new StringBuilder();
            sb.append("# Minecraft server.properties generated by %s\n".formatted(botInfoHolder.getBotLink()));
            sb.append("# Для сервера версии: %s\n\n".formatted(versionInput));

            for (ServerProperty prop : properties) {
                ServerPropertiesUtils.appendFormattedComment(sb, prop.getDescription());
                if (prop.getRecommendation() != null && !prop.getRecommendation().isEmpty()) {
                    ServerPropertiesUtils.appendFormattedComment(sb, "Рекомендация: " + prop.getRecommendation());
                }
                sb.append(prop.getParameter())
                        .append("=")
                        .append(prop.getDefaultValue())
                        .append("\n\n");
            }
            byte[] fileBytes = sb.toString().getBytes(StandardCharsets.UTF_8);
            SendDocument doc = new SendDocument(chatId, fileBytes)
                    .fileName("server.properties")
                    .caption("Готово! Вот ваш файл настроек для версии " + versionInput);

            responses.add(doc);
            responses.add(startHandler.getWelcomeMessage(chatId));

            return new HandlerResult(responses, BotState.MAIN_MENU);
        }
        // Пользователь отправил невалидный ответ
        SendMessage response = new SendMessage(chatId, "*Введите версию игры* \\(например: `1\\.16\\.5`\\)," +
                " или отправьте свой `server.properties` чтобы получить готовый файл\\.")
                .parseMode(ParseMode.MarkdownV2);

        // Кнопка отмены с действием CANCEL_INPUT
        InlineKeyboardMarkup keyboard = new InlineKeyboardMarkup(
                new InlineKeyboardButton("В меню")
                        .callbackData(BotAction.CANCEL_INPUT.getCallbackData())
        );
        response.replyMarkup(keyboard);
        return new HandlerResult(List.of(response), null);
    }
}
